language: objective-c  #1
osx_image: xcode9.3beta

jobs:
  include:
    - script: xcodebuild clean build test -project 'Floh Assignment.xcodeproj' -scheme 'Floh Assignment' -destination "platform=iOS Simulator,name=iPhone 8,OS=11.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
